apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-management
  template:
    metadata:
      labels:
        app: transaction-management
    spec:
      containers:
      - name: transaction-management
        image: transaction-management:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-management
spec:
  selector:
    app: transaction-management
  ports:
  - port: 8081
    targetPort: 8080
  type: LoadBalancer 